from sqlalchemy.orm import Session
from models import (
    SessionLocal,
    engine,
    Base,
    Property,
    UnitType,
    UnitImage,
    UnitCategory,
)
import datetime

# 1. Open a connection
db = SessionLocal()


def seed_data():
    print(" Seeding data...")

    # --- PROPERTY 1: Victor Heights (Ruaka) ---
    print("... Creating Victor Heights")
    victor_heights = Property(
        name="Victor Heights",
        slug="victor-heights-ruaka",
        address="123 Limuru Road",
        city="Ruaka",
        neighborhood="Ruaka",
        has_parking=True,
        has_security=True,
        has_borehole=True,
    )
    db.add(victor_heights)
    db.flush()  # Flush to get the ID generated by the DB

    # Unit Type 1: 2 Bedroom
    vh_2bed = UnitType(
        property_id=victor_heights.id,
        name="Premium 2 Bedroom",
        category=UnitCategory.two_bedroom,
        price_per_month=25000.00,
        deposit_amount=25000.00,
        total_units_count=10,
        available_units_count=3,  # 3 are vacant!
        description="Spacious master ensuite with large balcony.",
    )
    db.add(vh_2bed)
    db.flush()

    # Images for 2 Bedroom
    db.add(
        UnitImage(
            unit_type_id=vh_2bed.id,
            image_url="https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
            caption="Living Room",
            is_primary=True,
        )
    )
    db.add(
        UnitImage(
            unit_type_id=vh_2bed.id,
            image_url="https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
            caption="Kitchen",
        )
    )

    # Unit Type 2: Bedsitter
    vh_bedsitter = UnitType(
        property_id=victor_heights.id,
        name="Standard Bedsitter",
        category=UnitCategory.bedsitter,
        price_per_month=8000.00,
        deposit_amount=8000.00,
        total_units_count=20,
        available_units_count=0,  # FULL! (Good for testing waitlist)
        description="Cozy bedsitter with instant shower and tiled floors.",
    )
    db.add(vh_bedsitter)
    db.flush()

    # Images for Bedsitter
    db.add(
        UnitImage(
            unit_type_id=vh_bedsitter.id,
            image_url="https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
            caption="Main Room",
            is_primary=True,
        )
    )

    # --- PROPERTY 2: Sunrise Villas (Westlands) ---
    print("... Creating Sunrise Villas")
    sunrise = Property(
        name="Sunrise Villas",
        slug="sunrise-villas-westlands",
        address="45 Waiyaki Way",
        city="Nairobi",
        neighborhood="Westlands",
        has_parking=True,
        has_security=True,
        has_borehole=False,
    )
    db.add(sunrise)
    db.flush()

    # Unit Type: 3 Bedroom
    sv_3bed = UnitType(
        property_id=sunrise.id,
        name="Luxury 3 Bedroom Penthouse",
        category=UnitCategory.three_bedroom,
        price_per_month=85000.00,
        deposit_amount=170000.00,
        total_units_count=5,
        available_units_count=1,
        description="Executive finishing with gym and pool access.",
    )
    db.add(sv_3bed)
    db.flush()

    # Images for 3 Bedroom
    db.add(
        UnitImage(
            unit_type_id=sv_3bed.id,
            image_url="https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
            caption="Exterior",
            is_primary=True,
        )
    )

    # Commit all changes
    db.commit()
    print(" Data seeded successfully!")
    db.close()


if __name__ == "__main__":
    seed_data()
