"""add_guest_id_to_appointments

Revision ID: 149a5c59c5b7
Revises: 750d3c5ecf76
Create Date: 2025-12-13 14:04:30.792978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149a5c59c5b7'
down_revision: Union[str, None] = '750d3c5ecf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('guest_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'guest_id')
    # ### end Alembic commands ###
