"""Add additional fees to unit_types

Revision ID: 23801035ee98
Revises: bceab7ecf01b
Create Date: 2025-12-10 23:14:03.648111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23801035ee98'
down_revision: Union[str, None] = 'bceab7ecf01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_types', sa.Column('agreement_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('unit_types', sa.Column('garbage_fee_monthly', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('unit_types', sa.Column('other_fees', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit_types', 'other_fees')
    op.drop_column('unit_types', 'garbage_fee_monthly')
    op.drop_column('unit_types', 'agreement_fee')
    # ### end Alembic commands ###
