"""Add internet fee to unit types

Revision ID: 3d50850b3003
Revises: ba7be2d3a4ad
Create Date: 2025-12-10 23:34:19.014580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d50850b3003'
down_revision: Union[str, None] = 'ba7be2d3a4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_types', sa.Column('internet_fee_monthly', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit_types', 'internet_fee_monthly')
    # ### end Alembic commands ###
