"""Add guest support to vacancy alerts

Revision ID: 65a46f147c28
Revises: 3d50850b3003
Create Date: 2025-12-11 14:00:40.066327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a46f147c28'
down_revision: Union[str, None] = '3d50850b3003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('vacancy_alerts', sa.Column('guest_id', sa.String(), nullable=True))
    op.add_column('vacancy_alerts', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('vacancy_alerts', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('vacancy_alerts', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('vacancy_alerts', sa.Column('special_requests', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy_alerts', 'special_requests')
    op.drop_column('vacancy_alerts', 'contact_phone')
    op.drop_column('vacancy_alerts', 'contact_email')
    op.drop_column('vacancy_alerts', 'contact_name')
    op.drop_column('vacancy_alerts', 'guest_id')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
