"""Add latitude and longitude to properties

Revision ID: 750d3c5ecf76
Revises: aa291de26ae0
Create Date: 2025-12-13 01:55:38.383215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750d3c5ecf76'
down_revision: Union[str, None] = 'aa291de26ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    # ### end Alembic commands ###
