"""Add primary_image_url and description to properties

Revision ID: aa291de26ae0
Revises: 58f22368ad25
Create Date: 2025-12-13 00:10:14.795558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa291de26ae0'
down_revision: Union[str, None] = '58f22368ad25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('primary_image_url', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('description', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_saved_properties_id'), table_name='saved_properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_saved_properties_id'), 'saved_properties', ['id'], unique=False)
    op.drop_column('properties', 'description')
    op.drop_column('properties', 'primary_image_url')
    # ### end Alembic commands ###
