"""Add water fee to unit types

Revision ID: ba7be2d3a4ad
Revises: 23801035ee98
Create Date: 2025-12-10 23:28:52.335637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7be2d3a4ad'
down_revision: Union[str, None] = '23801035ee98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_types', sa.Column('water_fee_monthly', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit_types', 'water_fee_monthly')
    # ### end Alembic commands ###
